kind: pipeline
name: docker-cilium

trigger:
  branch:
    - dev

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

workspace:
  path: /go/src/github.com/cilium/cilium

clone:
  disable: true

steps:
  - name: s3-cache
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-s3-cache:1.0
    settings:
      restore: true
      mount:
        - ./.git
      endpoint: https://cache.wodcloud.com
      access_key:
        from_secret: ACCESS_KEY_MINIO
      secret_key:
        from_secret: SECRET_KEY_MINIO

  - name: fetch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    settings:
      proxy:
        from_secret: SOCKS5_PROXY

  - name: golang-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod-arm/cilium-builder:v1.9-20210814-amd64
    environment:
      GOPROXY: https://goproxy.cn
      TARGETOS: linux
      TARGETARCH: amd64
    commands:
      - bash .beagle/cilium/build.sh

  - name: golang-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod-arm/cilium-builder:v1.9-20220412-cross
    environment:
      GOPROXY: https://goproxy.cn
      TARGETOS: linux
      TARGETARCH: arm64
      GOARCH: arm64
      CC: aarch64-linux-gnu-gcc
    commands:
      - bash .beagle/cilium/build.sh

  - name: golang-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod-arm/cilium-builder:v1.9-20220412-cross
    environment:
      GOPROXY: https://goproxy.cn
      TARGETOS: linux
      TARGETARCH: ppc64le
      GOARCH: ppc64le
      CC: powerpc64le-linux-gnu-gcc
    commands:
      - bash .beagle/cilium/build.sh

  - name: docker-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/cilium/dockerfile
      cwd: ./.buildx/cilium/linux/amd64
      base: registry.cn-qingdao.aliyuncs.com/wod-arm/cilium-runtime:v1.9-20211011-amd64
      repo: wod/cilium
      version: v1.11.18
      channel: amd64
      args: 'TARGETOS=linux,TARGETARCH=amd64'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/cilium/dockerfile
      cwd: ./.buildx/cilium/linux/arm64
      base: registry.cn-qingdao.aliyuncs.com/wod-arm/cilium-runtime:v1.9-20211011-arm64
      repo: wod/cilium
      version: v1.11.18
      channel: arm64
      args: 'TARGETOS=linux,TARGETARCH=arm64'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/cilium/dockerfile
      cwd: ./.buildx/cilium/linux/ppc64le
      base: registry.cn-qingdao.aliyuncs.com/wod-arm/cilium-runtime:v1.9-20211011-ppc64le
      repo: wod/cilium
      version: v1.11.18
      channel: ppc64le
      args: 'TARGETOS=linux,TARGETARCH=ppc64le'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: pipeline
name: docker-cilium-hubble-relay

trigger:
  branch:
    - dev

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

workspace:
  path: /go/src/github.com/cilium/cilium

clone:
  disable: true

steps:
  - name: s3-cache
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-s3-cache:1.0
    settings:
      restore: true
      mount:
        - ./.git
      endpoint: https://cache.wodcloud.com
      access_key:
        from_secret: ACCESS_KEY_MINIO
      secret_key:
        from_secret: SECRET_KEY_MINIO

  - name: fetch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    settings:
      proxy:
        from_secret: SOCKS5_PROXY

  - name: golang-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod-arm/cilium-builder:v1.9-20210814-amd64
    environment:
      GOPROXY: https://goproxy.cn
      TARGETOS: linux
      TARGETARCH: amd64
    commands:
      - bash .beagle/hubble-relay/build.sh

  - name: golang-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod-arm/cilium-builder:v1.9-20220412-cross
    environment:
      GOPROXY: https://goproxy.cn
      TARGETOS: linux
      TARGETARCH: arm64
      GOARCH: arm64
      CC: aarch64-linux-gnu-gcc
    commands:
      - bash .beagle/hubble-relay/build.sh

  - name: golang-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod-arm/cilium-builder:v1.9-20220412-cross
    environment:
      GOPROXY: https://goproxy.cn
      TARGETOS: linux
      TARGETARCH: ppc64le
      GOARCH: ppc64le
      CC: powerpc64le-linux-gnu-gcc
    commands:
      - bash .beagle/hubble-relay/build.sh

  - name: docker-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/hubble-relay/dockerfile
      cwd: ./.buildx/hubble-relay/linux/amd64
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3-amd64
      repo: wod/cilium-hubble-relay
      version: v1.11.18
      channel: amd64
      args: 'TARGETOS=linux,TARGETARCH=amd64'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/hubble-relay/dockerfile
      cwd: ./.buildx/hubble-relay/linux/arm64
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3-arm64
      repo: wod/cilium-hubble-relay
      version: v1.11.18
      channel: arm64
      args: 'TARGETOS=linux,TARGETARCH=arm64'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/hubble-relay/dockerfile
      cwd: ./.buildx/hubble-relay/linux/ppc64le
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3-ppc64le
      repo: wod/cilium-hubble-relay
      version: v1.11.18
      channel: ppc64le
      args: 'TARGETOS=linux,TARGETARCH=ppc64le'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: pipeline
name: docker-cilium-operator-generic

trigger:
  branch:
    - dev

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

workspace:
  path: /go/src/github.com/cilium/cilium

clone:
  disable: true

steps:
  - name: s3-cache
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-s3-cache:1.0
    settings:
      restore: true
      mount:
        - ./.git
      endpoint: https://cache.wodcloud.com
      access_key:
        from_secret: ACCESS_KEY_MINIO
      secret_key:
        from_secret: SECRET_KEY_MINIO

  - name: fetch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    settings:
      proxy:
        from_secret: SOCKS5_PROXY

  - name: golang-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod-arm/cilium-builder:v1.9-20210814-amd64
    environment:
      GOPROXY: https://goproxy.cn
      TARGETOS: linux
      TARGETARCH: amd64
    commands:
      - bash .beagle/operator-generic/build.sh

  - name: golang-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod-arm/cilium-builder:v1.9-20220412-cross
    environment:
      GOPROXY: https://goproxy.cn
      TARGETOS: linux
      TARGETARCH: arm64
      GOARCH: arm64
      CC: aarch64-linux-gnu-gcc
    commands:
      - bash .beagle/operator-generic/build.sh

  - name: golang-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod-arm/cilium-builder:v1.9-20220412-cross
    environment:
      GOPROXY: https://goproxy.cn
      TARGETOS: linux
      TARGETARCH: ppc64le
      GOARCH: ppc64le
      CC: powerpc64le-linux-gnu-gcc
    commands:
      - bash .beagle/operator-generic/build.sh

  - name: docker-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/operator-generic/dockerfile
      cwd: ./.buildx/operator-generic/linux/amd64
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3-amd64
      repo: wod/cilium-operator-generic
      version: v1.11.18
      channel: amd64
      args: 'TARGETOS=linux,TARGETARCH=amd64'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/operator-generic/dockerfile
      cwd: ./.buildx/operator-generic/linux/arm64
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3-arm64
      repo: wod/cilium-operator-generic
      version: v1.11.18
      channel: arm64
      args: 'TARGETOS=linux,TARGETARCH=arm64'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/operator-generic/dockerfile
      cwd: ./.buildx/operator-generic/linux/ppc64le
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3-ppc64le
      repo: wod/cilium-operator-generic
      version: v1.11.18
      channel: ppc64le
      args: 'TARGETOS=linux,TARGETARCH=ppc64le'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: pipeline
name: harbor-cilium

trigger:
  branch:
    - main

clone:
  disable: true

steps:

  - name: docker-arch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:1.0
    settings:
      platforms: linux/amd64,linux/arm64,linux/ppc64le
      template: registry.cn-qingdao.aliyuncs.com/wod/cilium:v1.11.18-ARCH
      target: registry.cn-qingdao.aliyuncs.com/wod/cilium:v1.11.18
      username:
        from_secret: REGISTRY_USER_ALIYUN
      password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: pipeline
name: harbor-cilium-hubble-relay

trigger:
  branch:
    - main

clone:
  disable: true

steps:

  - name: docker-arch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:1.0
    settings:
      platforms: linux/amd64,linux/arm64,linux/ppc64le
      template: registry.cn-qingdao.aliyuncs.com/wod/cilium-hubble-relay:v1.11.18-ARCH
      target: registry.cn-qingdao.aliyuncs.com/wod/cilium-hubble-relay:v1.11.18
      username:
        from_secret: REGISTRY_USER_ALIYUN
      password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: pipeline
name: harbor-cilium-operator-generic

trigger:
  branch:
    - main

clone:
  disable: true

steps:

  - name: docker-arch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:1.0
    settings:
      platforms: linux/amd64,linux/arm64,linux/ppc64le
      template: registry.cn-qingdao.aliyuncs.com/wod/cilium-operator-generic:v1.11.18-ARCH
      target: registry.cn-qingdao.aliyuncs.com/wod/cilium-operator-generic:v1.11.18
      username:
        from_secret: REGISTRY_USER_ALIYUN
      password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: secret
name: SOCKS5_PROXY
get:
  name: SOCKS5_PROXY
  path: devops-secrets

---
kind: secret
name: REGISTRY_USER_ALIYUN
get:
  name: REGISTRY_USER_ALIYUN
  path: devops-secrets

---
kind: secret
name: REGISTRY_PASSWORD_ALIYUN
get:
  name: REGISTRY_PASSWORD_ALIYUN
  path: devops-secrets

---
kind: secret
name: ACCESS_KEY_MINIO
get:
  name: ACCESS_KEY_MINIO
  path: devops-secrets

---
kind: secret
name: SECRET_KEY_MINIO
get:
  name: SECRET_KEY_MINIO
  path: devops-secrets
