ARG BASE

FROM $BASE

ARG AUTHOR
ARG VERSION

LABEL maintainer=$AUTHOR version=$VERSION

ARG TARGETOS
ARG TARGETARCH

COPY ./usr/bin/cilium-operator-generic /usr/bin/cilium-operator-generic

WORKDIR /
ENV GOPS_CONFIG_DIR=/

CMD ["/usr/bin/cilium-operator-generic"]
